- name: Install required dependencies
  apt:
     name: "{{ packages }}"
     state: installed
  vars:
     packages:
     - make
     - git
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add user for Athens
  user:
    name: athens

- name: Creating required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: athens
  with_items:
  - ["{{ install_prefix }}/etc/athens", "{{ install_prefix }}/etc/athens/pki","/usr/local/share/athens"]

- name: Check if GO binary exist
  stat:
    path: "{{ install_prefix }}/go/bin/go"
  register: stat_result

- name: Download GO if need
  unarchive:
    src: https://dl.google.com/go/go{{ GO_VERSION }}.{{ ARCH }}.tar.gz
    dest: "{{ install_prefix }}/"
    remote_src: yes
    mode: 0755
  when: stat_result.stat.exists == false

- name: Create symbolic link for GO binary
  file:
    src: "{{ install_prefix }}/go/bin/go"
    dest: "/usr/local/bin/go"
    state: link
  when: stat_result.stat.exists == false

- name: Clone Athens git-repository
  git:
    repo: https://github.com/gomods/athens
    dest: /tmp/athens

- name: Make Athens binary
  command: make build-ver VERSION="{{ ATHENS_VERSION }}"
  args:
    chdir: /tmp/athens

- name: Move Athens binary to bin directory
  copy:
    src: "/tmp/athens/athens"
    dest: "{{ install_prefix }}/bin/athens"
    owner: athens
    mode: 0750

- name: Copy systemd template for Athens
  template:
    src: athens.service
    dest: "/etc/systemd/system/athens.service"
    owner: root
    group: root
    mode: 0644

- name: Copy config file for Athens
  template:
    src: config.toml
    dest: "{{ install_prefix }}/etc/athens/config.toml"
    owner: athens
    mode: 0640
