- name: Install required dependencies
  apt:
     name: "{{ packages }}"
     state: installed
  vars:
     packages:
     - curl
     - ca-certificates
     - postfix
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Add user for Gitlab-runner
  user:
    name: gitlab-runner

- name: Creating required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: gitlab-runner
  with_items:
  - ["{{ install_prefix }}/etc/gitlab-runner", "{{ install_prefix }}/etc/gitlab-runner/pki","/usr/local/share/gitlab-runner"]

- name: Check if GO binary exist
  stat:
    path: "{{ install_prefix }}/go/bin/go"
  register: stat_result

- name: Download GO if need
  unarchive:
    src: https://dl.google.com/go/go{{ GO_VERSION }}.{{ ARCH }}.tar.gz
    dest: "{{ install_prefix }}/"
    remote_src: yes
    mode: 0755
  when: stat_result.stat.exists == false

- name: Create symbolic link for GO binary
  file:
    src: "{{ install_prefix }}/go/bin/go"
    dest: "/usr/local/bin/go"
    state: link
  when: stat_result.stat.exists == false

- name: Download gitlab-runner binary
  get_url:
    url: https://gitlab-runner-downloads.s3.amazonaws.com/v{{ RUNNER_VERSION }}/binaries/gitlab-runner-{{ ARCH }}
    dest: "{{ install_prefix }}/bin/gitlab-runner"
    mode: 0755

- name: Copy systemd template for Gitlab-runner
  template:
    src: gitlab-runner.service
    dest: "/etc/systemd/system/gitlab-runner.service"
    owner: root
    group: root
    mode: 0644

- name: Copy config file for Gitlab-runner
  template:
    src: config.toml
    dest: "{{ install_prefix }}/etc/gitlab-runner/config.toml"
    owner: gitlab-runner
    mode: 0640

- name: Register gitlab-runner
  command: gitlab-runner register --non-interactive --name {{ RUNNER_NAME }} --url {{ RUNNER_SRV }} --registration-token {{ RUNNER_REGTOKEN }} --locked=false --executor {{ RUNNER_EXECUTOR }} --config "/tmp/gitlab-config.toml"

- name: Insert runner token into configuration
  raw: TMP=`cat /tmp/gitlab-config.toml | awk '/token/ {print $3}'` && sed -i 's@RUNNER_TOKEN@'"$TMP"'@g' "{{ install_prefix }}/etc/gitlab-runner/config.toml"

- name: Remove temporary config
  file:
    state: absent
    path: "/tmp/gitlab-config.toml"

- name: Enable and start Gitlab-runner systemd service
  systemd:
    name: gitlab-runner.service
    state: started
    enabled: yes
    daemon_reload: yes
